version: '3.8'

services:
  superapp:
    image: nejer/superapp:latest
    restart: unless-stopped
    container_name: superapp_container
    ports:
      - "5000:5000"
    volumes:
      - ./servers/.node-persist:/app/servers/.node-persist